# questions.py

question_bank = {

# ================= PYTHON DEVELOPER =================
"Python Developer": [
{"question": "What is Python?", "answer": "Python is a high level object oriented programming language."},
{"question": "What are Python data types?", "answer": "Common data types include list tuple set dictionary string and integer."},
{"question": "Explain OOP concepts in Python.", "answer": "OOP includes encapsulation inheritance polymorphism abstraction."},
{"question": "What is list comprehension?", "answer": "List comprehension creates lists in single concise syntax."},
{"question": "What is lambda function?", "answer": "Lambda is an anonymous function."},
{"question": "What is decorator?", "answer": "Decorator modifies function behavior."},
{"question": "What is generator?", "answer": "Generator yields values using yield keyword."},
{"question": "What is multithreading?", "answer": "Multithreading executes multiple threads concurrently."},
{"question": "What is multiprocessing?", "answer": "Multiprocessing runs multiple processes in parallel."},
{"question": "What is GIL?", "answer": "GIL is Global Interpreter Lock limiting threads execution."},
{"question": "What is exception handling?", "answer": "Exception handling manages runtime errors."},
{"question": "What is try except block?", "answer": "Try except handles exceptions."},
{"question": "What is virtual environment?", "answer": "Virtual environment isolates project dependencies."},
{"question": "What is pip?", "answer": "Pip installs Python packages."},
{"question": "What is Flask?", "answer": "Flask is lightweight Python web framework."},
{"question": "What is Django?", "answer": "Django is full featured Python web framework."},
{"question": "What is REST API?", "answer": "REST API enables HTTP based communication."},
{"question": "What is JSON?", "answer": "JSON is lightweight data exchange format."},
{"question": "What is recursion?", "answer": "Recursion is function calling itself."},
{"question": "What is module?", "answer": "Module is Python file containing code."},
{"question": "What is package?", "answer": "Package is collection of modules."},
{"question": "Explain __init__ method.", "answer": "__init__ initializes object attributes."},
{"question": "What is SQLite?", "answer": "SQLite is lightweight relational database."},
{"question": "What is ORM?", "answer": "ORM maps objects to database tables."},
{"question": "What is Pandas?", "answer": "Pandas is data analysis library."},
{"question": "What is NumPy?", "answer": "NumPy is numerical computing library."},
{"question": "What is matplotlib?", "answer": "Matplotlib is visualization library."},
{"question": "What is API?", "answer": "API enables communication between systems."},
{"question": "What is threading?", "answer": "Threading runs concurrent tasks."},
{"question": "What is file handling?", "answer": "File handling reads and writes files."},
{"question": "What is with statement?", "answer": "With manages resources safely."},
{"question": "Difference between list and tuple?", "answer": "List is mutable tuple is immutable."},
{"question": "What is dictionary?", "answer": "Dictionary stores key value pairs."},
{"question": "What is set?", "answer": "Set stores unique elements."},
{"question": "What is shallow copy?", "answer": "Shallow copy copies references."},
{"question": "What is deep copy?", "answer": "Deep copy copies objects recursively."},
{"question": "What is docstring?", "answer": "Docstring documents functions."},
{"question": "What is pep8?", "answer": "PEP8 defines coding style guidelines."},
{"question": "What is async await?", "answer": "Async await handles asynchronous operations."},
{"question": "What is yield keyword?", "answer": "Yield returns generator value."},
{"question": "Explain map filter reduce.", "answer": "Map filter reduce perform functional operations."},
{"question": "What is SQLAlchemy?", "answer": "SQLAlchemy is Python ORM library."},
{"question": "What is pytest?", "answer": "Pytest is testing framework."},
{"question": "What is unit testing?", "answer": "Unit testing tests individual components."},
{"question": "What is logging module?", "answer": "Logging tracks program execution."},
{"question": "What is serialization?", "answer": "Serialization converts object to byte stream."},
{"question": "What is deserialization?", "answer": "Deserialization converts byte stream to object."},
{"question": "Explain Python memory management.", "answer": "Python uses reference counting and garbage collection."},
{"question": "What is dynamic typing?", "answer": "Dynamic typing assigns type at runtime."},
{"question": "Explain Python project architecture.", "answer": "Python project uses modular layered architecture."}
],

# ================= JAVA DEVELOPER =================
"Java Developer": [
{"question": "What is Java?", "answer": "Java is object oriented programming language."},
{"question": "What is JVM?", "answer": "JVM executes Java bytecode."},
{"question": "What is JDK?", "answer": "JDK provides development tools."},
{"question": "What is JRE?", "answer": "JRE provides runtime environment."},
{"question": "Explain OOP in Java.", "answer": "OOP includes encapsulation inheritance polymorphism abstraction."},
{"question": "What is Spring Boot?", "answer": "Spring Boot builds production ready applications."},
{"question": "What is Hibernate?", "answer": "Hibernate is ORM framework."},
{"question": "What is multithreading?", "answer": "Multithreading runs threads concurrently."},
{"question": "What is collection framework?", "answer": "Collection framework manages object groups."},
{"question": "What is ArrayList?", "answer": "ArrayList is dynamic array."},
{"question": "What is HashMap?", "answer": "HashMap stores key value pairs."},
{"question": "What is exception?", "answer": "Exception is runtime error."},
{"question": "What is try catch?", "answer": "Try catch handles exceptions."},
{"question": "What is garbage collection?", "answer": "Garbage collection frees memory."},
{"question": "What is JDBC?", "answer": "JDBC connects Java to database."},
{"question": "What is interface?", "answer": "Interface defines abstract methods."},
{"question": "What is abstract class?", "answer": "Abstract class cannot be instantiated."},
{"question": "What is lambda expression?", "answer": "Lambda enables functional programming."},
{"question": "What is stream API?", "answer": "Stream API processes collections."},
{"question": "What is REST API?", "answer": "REST API uses HTTP methods."},
{"question": "What is Maven?", "answer": "Maven manages dependencies."},
{"question": "What is Gradle?", "answer": "Gradle automates build process."},
{"question": "What is microservices?", "answer": "Microservices split application into services."},
{"question": "What is servlet?", "answer": "Servlet handles web requests."},
{"question": "What is JSP?", "answer": "JSP builds dynamic web pages."},
{"question": "What is synchronization?", "answer": "Synchronization controls thread access."},
{"question": "What is singleton pattern?", "answer": "Singleton ensures single instance."},
{"question": "What is MVC?", "answer": "MVC separates model view controller."},
{"question": "What is encapsulation?", "answer": "Encapsulation hides data."},
{"question": "What is polymorphism?", "answer": "Polymorphism allows multiple forms."},
{"question": "What is inheritance?", "answer": "Inheritance acquires properties."},
{"question": "What is abstraction?", "answer": "Abstraction hides implementation."},
{"question": "What is final keyword?", "answer": "Final restricts modification."},
{"question": "What is static keyword?", "answer": "Static belongs to class."},
{"question": "What is memory management?", "answer": "Memory management handles allocation."},
{"question": "Explain stack vs heap.", "answer": "Stack stores local heap stores objects."},
{"question": "What is String pool?", "answer": "String pool stores string literals."},
{"question": "What is comparator?", "answer": "Comparator sorts objects."},
{"question": "What is Comparable?", "answer": "Comparable defines natural ordering."},
{"question": "What is thread lifecycle?", "answer": "Thread lifecycle defines thread states."},
{"question": "What is reflection?", "answer": "Reflection inspects classes at runtime."},
{"question": "What is serialization?", "answer": "Serialization converts object to stream."},
{"question": "What is deserialization?", "answer": "Deserialization converts stream to object."},
{"question": "What is optional class?", "answer": "Optional avoids null pointer."},
{"question": "What is dependency injection?", "answer": "Dependency injection supplies dependencies."},
{"question": "What is API?", "answer": "API allows system interaction."},
{"question": "What is unit testing?", "answer": "Unit testing tests components."},
{"question": "What is JUnit?", "answer": "JUnit is Java testing framework."},
{"question": "Explain Java architecture.", "answer": "Java architecture includes JDK JRE JVM."},
{"question": "Explain Java project structure.", "answer": "Java project follows layered architecture."}
],
"MERN Stack Developer": [
{"question":"What is MongoDB?","answer":"MongoDB is NoSQL document database."},
{"question":"What is Express.js?","answer":"Express is Node.js web framework."},
{"question":"What is React?","answer":"React is JavaScript UI library."},
{"question":"What is Node.js?","answer":"Node.js runs JavaScript on server."},
{"question":"What is Mongoose?","answer":"Mongoose is ODM for MongoDB."},
{"question":"What is REST API?","answer":"REST API enables HTTP communication."},
{"question":"What is JWT?","answer":"JWT is token based authentication."},
{"question":"What is middleware?","answer":"Middleware handles request response cycle."},
{"question":"What is Redux?","answer":"Redux manages application state."},
{"question":"What is Context API?","answer":"Context API shares global state."},
{"question":"What is Virtual DOM?","answer":"Virtual DOM optimizes rendering."},
{"question":"What is useState?","answer":"useState manages component state."},
{"question":"What is useEffect?","answer":"useEffect handles side effects."},
{"question":"What is async await?","answer":"Async await handles asynchronous code."},
{"question":"What is CORS?","answer":"CORS controls cross origin access."},
{"question":"What is MVC?","answer":"MVC separates model view controller."},
{"question":"What is CRUD?","answer":"CRUD means create read update delete."},
{"question":"What is SSR?","answer":"SSR renders on server side."},
{"question":"What is CSR?","answer":"CSR renders on client side."},
{"question":"What is deployment?","answer":"Deployment makes application live."},
{"question":"What is environment variable?","answer":"Environment variable stores config."},
{"question":"What is npm?","answer":"npm manages Node packages."},
{"question":"What is package.json?","answer":"package.json stores project metadata."},
{"question":"What is hashing?","answer":"Hashing secures passwords."},
{"question":"What is bcrypt?","answer":"bcrypt hashes passwords securely."},
{"question":"What is socket.io?","answer":"Socket.io enables real time communication."},
{"question":"What is API testing?","answer":"API testing validates endpoints."},
{"question":"What is Postman?","answer":"Postman tests APIs."},
{"question":"What is aggregation in MongoDB?","answer":"Aggregation processes data records."},
{"question":"What is indexing?","answer":"Indexing improves query performance."},
{"question":"What is authentication?","answer":"Authentication verifies identity."},
{"question":"What is authorization?","answer":"Authorization controls access."},
{"question":"What is Express Router?","answer":"Router manages routes."},
{"question":"What is props in React?","answer":"Props pass data to components."},
{"question":"What is state in React?","answer":"State stores component data."},
{"question":"What is event loop?","answer":"Event loop handles async tasks."},
{"question":"What is promise?","answer":"Promise represents future value."},
{"question":"What is Netlify?","answer":"Netlify hosts frontend apps."},
{"question":"What is Vercel?","answer":"Vercel deploys web apps."},
{"question":"What is scalability?","answer":"Scalability handles growth."},
{"question":"What is error handling?","answer":"Error handling manages runtime errors."},
{"question":"Explain MERN architecture.","answer":"MERN uses Mongo Express React Node stack."},
{"question":"What is SPA?","answer":"SPA is single page application."},
{"question":"What is responsive design?","answer":"Responsive design adapts layouts."},
{"question":"What is React Router?","answer":"React Router handles navigation."},
{"question":"What is Helmet?","answer":"Helmet secures Express apps."},
{"question":"What is rate limiting?","answer":"Rate limiting controls traffic."},
{"question":"What is load balancing?","answer":"Load balancing distributes traffic."},
{"question":"What is clustering?","answer":"Clustering improves performance."},
{"question":"Explain your MERN project.","answer":"MERN project follows full stack architecture."}
],
"Data Scientist": [
{"question":"What is Data Science?","answer":"Data science extracts insights from data."},
{"question":"What is Machine Learning?","answer":"Machine learning allows systems to learn from data."},
{"question":"What is supervised learning?","answer":"Supervised learning uses labeled data."},
{"question":"What is unsupervised learning?","answer":"Unsupervised learning finds hidden patterns."},
{"question":"What is regression?","answer":"Regression predicts continuous values."},
{"question":"What is classification?","answer":"Classification predicts categories."},
{"question":"What is overfitting?","answer":"Overfitting fits training data too closely."},
{"question":"What is underfitting?","answer":"Underfitting fails to capture patterns."},
{"question":"What is cross validation?","answer":"Cross validation evaluates model performance."},
{"question":"What is feature engineering?","answer":"Feature engineering creates useful input variables."},
{"question":"What is normalization?","answer":"Normalization scales data values."},
{"question":"What is standardization?","answer":"Standardization centers data."},
{"question":"What is Pandas?","answer":"Pandas handles data analysis."},
{"question":"What is NumPy?","answer":"NumPy supports numerical computing."},
{"question":"What is Matplotlib?","answer":"Matplotlib visualizes data."},
{"question":"What is Seaborn?","answer":"Seaborn improves data visualization."},
{"question":"What is SQL?","answer":"SQL queries relational databases."},
{"question":"What is EDA?","answer":"EDA explores data patterns."},
{"question":"What is confusion matrix?","answer":"Confusion matrix evaluates classification."},
{"question":"What is precision?","answer":"Precision measures positive accuracy."},
{"question":"What is recall?","answer":"Recall measures detection rate."},
{"question":"What is F1 score?","answer":"F1 balances precision and recall."},
{"question":"What is ROC curve?","answer":"ROC shows model performance."},
{"question":"What is AUC?","answer":"AUC measures classifier quality."},
{"question":"What is clustering?","answer":"Clustering groups similar data."},
{"question":"What is KMeans?","answer":"KMeans clusters data points."},
{"question":"What is PCA?","answer":"PCA reduces dimensionality."},
{"question":"What is neural network?","answer":"Neural network mimics human brain."},
{"question":"What is deep learning?","answer":"Deep learning uses multi layer networks."},
{"question":"What is NLP?","answer":"NLP processes natural language."},
{"question":"What is TensorFlow?","answer":"TensorFlow builds ML models."},
{"question":"What is PyTorch?","answer":"PyTorch builds deep learning models."},
{"question":"What is bias variance tradeoff?","answer":"Tradeoff balances bias and variance."},
{"question":"What is gradient descent?","answer":"Gradient descent optimizes models."},
{"question":"What is hyperparameter tuning?","answer":"Hyperparameter tuning improves model."},
{"question":"What is big data?","answer":"Big data handles large datasets."},
{"question":"What is Hadoop?","answer":"Hadoop processes big data."},
{"question":"What is Spark?","answer":"Spark performs distributed computing."},
{"question":"What is data cleaning?","answer":"Data cleaning removes errors."},
{"question":"What is imbalanced data?","answer":"Imbalanced data skews classes."},
{"question":"What is ensemble learning?","answer":"Ensemble combines multiple models."},
{"question":"What is random forest?","answer":"Random forest uses decision trees."},
{"question":"What is SVM?","answer":"SVM is classification algorithm."},
{"question":"What is logistic regression?","answer":"Logistic regression predicts probability."},
{"question":"What is linear regression?","answer":"Linear regression predicts numeric output."},
{"question":"What is time series analysis?","answer":"Time series analyzes sequential data."},
{"question":"What is model deployment?","answer":"Model deployment makes model live."},
{"question":"What is data pipeline?","answer":"Data pipeline processes data flow."},
{"question":"Explain your data project.","answer":"Data project involves cleaning modeling and deployment."}
],
"DevOps Engineer": [
{"question":"What is DevOps?","answer":"DevOps integrates development and operations."},
{"question":"What is CI CD?","answer":"CI CD automates build and deployment."},
{"question":"What is Jenkins?","answer":"Jenkins is automation server."},
{"question":"What is Docker?","answer":"Docker containerizes applications."},
{"question":"What is Kubernetes?","answer":"Kubernetes orchestrates containers."},
{"question":"What is containerization?","answer":"Containerization packages app with dependencies."},
{"question":"What is Git?","answer":"Git is version control system."},
{"question":"What is GitHub?","answer":"GitHub hosts Git repositories."},
{"question":"What is branching strategy?","answer":"Branching strategy manages code versions."},
{"question":"What is Infrastructure as Code?","answer":"IaC manages infrastructure using code."},
{"question":"What is Terraform?","answer":"Terraform provisions infrastructure."},
{"question":"What is Ansible?","answer":"Ansible automates configuration management."},
{"question":"What is monitoring?","answer":"Monitoring tracks system health."},
{"question":"What is Prometheus?","answer":"Prometheus monitors metrics."},
{"question":"What is Grafana?","answer":"Grafana visualizes monitoring data."},
{"question":"What is load balancing?","answer":"Load balancing distributes traffic."},
{"question":"What is blue green deployment?","answer":"Blue green minimizes downtime."},
{"question":"What is rollback?","answer":"Rollback restores previous version."},
{"question":"What is scaling?","answer":"Scaling adjusts system capacity."},
{"question":"What is microservices?","answer":"Microservices split apps into services."},
{"question":"What is YAML?","answer":"YAML configures services."},
{"question":"What is Linux?","answer":"Linux is operating system."},
{"question":"What is shell scripting?","answer":"Shell scripting automates tasks."},
{"question":"What is AWS?","answer":"AWS provides cloud services."},
{"question":"What is Azure?","answer":"Azure is Microsoft cloud."},
{"question":"What is GCP?","answer":"GCP is Google cloud platform."},
{"question":"What is CDN?","answer":"CDN delivers content faster."},
{"question":"What is SSL?","answer":"SSL secures communication."},
{"question":"What is reverse proxy?","answer":"Reverse proxy forwards client requests."},
{"question":"Explain DevOps lifecycle.","answer":"DevOps lifecycle includes plan build test deploy monitor."},
{"question":"What is logging?","answer":"Logging tracks application events."},
{"question":"What is ELK stack?","answer":"ELK manages logs."},
{"question":"What is high availability?","answer":"High availability reduces downtime."},
{"question":"What is disaster recovery?","answer":"Disaster recovery restores systems."},
{"question":"What is automation testing?","answer":"Automation testing speeds validation."},
{"question":"What is pipeline?","answer":"Pipeline automates workflow."},
{"question":"What is artifact?","answer":"Artifact is build output."},
{"question":"What is versioning?","answer":"Versioning tracks software versions."},
{"question":"What is serverless?","answer":"Serverless runs without managing servers."},
{"question":"Explain Docker architecture.","answer":"Docker uses client server architecture."},
{"question":"Explain Kubernetes architecture.","answer":"Kubernetes manages pods and nodes."},
{"question":"What is pod?","answer":"Pod is smallest deployable unit."},
{"question":"What is Helm?","answer":"Helm manages Kubernetes packages."},
{"question":"What is secrets management?","answer":"Secrets management secures credentials."},
{"question":"What is SRE?","answer":"SRE ensures system reliability."},
{"question":"What is uptime?","answer":"Uptime measures availability."},
{"question":"What is latency?","answer":"Latency measures delay."},
{"question":"What is throughput?","answer":"Throughput measures performance."},
{"question":"Explain your DevOps project.","answer":"DevOps project automates build and deployment."}
],
"Cyber Security": [
{"question":"What is cyber security?","answer":"Cyber security protects systems from attacks."},
{"question":"What is malware?","answer":"Malware is malicious software."},
{"question":"What is phishing?","answer":"Phishing steals user credentials."},
{"question":"What is firewall?","answer":"Firewall filters network traffic."},
{"question":"What is encryption?","answer":"Encryption secures data."},
{"question":"What is hashing?","answer":"Hashing converts data into fixed string."},
{"question":"What is SSL?","answer":"SSL secures communication."},
{"question":"What is VPN?","answer":"VPN secures network connection."},
{"question":"What is DDoS?","answer":"DDoS overloads servers."},
{"question":"What is brute force attack?","answer":"Brute force tries all passwords."},
{"question":"What is XSS?","answer":"XSS injects malicious scripts."},
{"question":"What is SQL injection?","answer":"SQL injection manipulates database queries."},
{"question":"What is ethical hacking?","answer":"Ethical hacking tests security."},
{"question":"What is penetration testing?","answer":"Pen testing identifies vulnerabilities."},
{"question":"What is CIA triad?","answer":"Confidentiality integrity availability model."},
{"question":"What is IDS?","answer":"IDS detects intrusions."},
{"question":"What is IPS?","answer":"IPS prevents intrusions."},
{"question":"What is authentication?","answer":"Authentication verifies identity."},
{"question":"What is authorization?","answer":"Authorization grants access."},
{"question":"What is 2FA?","answer":"Two factor authentication adds security."},
{"question":"What is ransomware?","answer":"Ransomware encrypts user files."},
{"question":"What is social engineering?","answer":"Social engineering manipulates users."},
{"question":"What is zero day attack?","answer":"Zero day exploits unknown vulnerability."},
{"question":"What is SIEM?","answer":"SIEM monitors security events."},
{"question":"What is threat modeling?","answer":"Threat modeling identifies risks."},
{"question":"What is OWASP?","answer":"OWASP lists web vulnerabilities."},
{"question":"What is port scanning?","answer":"Port scanning checks open ports."},
{"question":"What is botnet?","answer":"Botnet is infected device network."},
{"question":"What is spyware?","answer":"Spyware monitors user activity."},
{"question":"What is trojan?","answer":"Trojan disguises malicious software."},
{"question":"What is patching?","answer":"Patching fixes vulnerabilities."},
{"question":"What is data breach?","answer":"Data breach exposes sensitive data."},
{"question":"What is network security?","answer":"Network security protects networks."},
{"question":"What is endpoint security?","answer":"Endpoint security protects devices."},
{"question":"What is cryptography?","answer":"Cryptography secures communication."},
{"question":"What is public key?","answer":"Public key encrypts data."},
{"question":"What is private key?","answer":"Private key decrypts data."},
{"question":"What is SOC?","answer":"SOC monitors security threats."},
{"question":"What is honeypot?","answer":"Honeypot traps attackers."},
{"question":"What is vulnerability?","answer":"Vulnerability is system weakness."},
{"question":"What is risk assessment?","answer":"Risk assessment analyzes threats."},
{"question":"What is compliance?","answer":"Compliance follows security standards."},
{"question":"What is ISO 27001?","answer":"ISO 27001 security standard."},
{"question":"What is GDPR?","answer":"GDPR protects user data."},
{"question":"Explain your security project.","answer":"Security project implemented secure authentication system."},
{"question":"What is MITM attack?","answer":"Man in the middle intercepts communication."},
{"question":"What is session hijacking?","answer":"Session hijacking steals user session."},
{"question":"What is secure coding?","answer":"Secure coding prevents vulnerabilities."},
{"question":"What is cloud security?","answer":"Cloud security protects cloud systems."},
{"question":"Why security important?","answer":"Security protects data and systems."}
],
"Frontend Developer": [
{"question":"What is HTML?","answer":"HTML structures web pages."},
{"question":"What is CSS?","answer":"CSS styles web pages."},
{"question":"What is JavaScript?","answer":"JavaScript adds interactivity."},
{"question":"What is DOM?","answer":"DOM represents webpage structure."},
{"question":"What is React?","answer":"React builds UI components."},
{"question":"What is component?","answer":"Component is reusable UI block."},
{"question":"What is state?","answer":"State stores component data."},
{"question":"What is props?","answer":"Props pass data to components."},
{"question":"What is JSX?","answer":"JSX combines HTML and JavaScript."},
{"question":"What is virtual DOM?","answer":"Virtual DOM optimizes rendering."},
{"question":"What is Bootstrap?","answer":"Bootstrap CSS framework."},
{"question":"What is Tailwind?","answer":"Tailwind utility CSS framework."},
{"question":"What is responsive design?","answer":"Responsive adapts to screens."},
{"question":"What is media query?","answer":"Media query styles by screen size."},
{"question":"What is API?","answer":"API connects frontend backend."},
{"question":"What is fetch?","answer":"Fetch retrieves data from server."},
{"question":"What is axios?","answer":"Axios handles HTTP requests."},
{"question":"What is SPA?","answer":"Single page application."},
{"question":"What is routing?","answer":"Routing manages navigation."},
{"question":"What is Redux?","answer":"Redux manages state globally."},
{"question":"What is useEffect?","answer":"useEffect handles side effects."},
{"question":"What is useState?","answer":"useState manages state."},
{"question":"What is event handling?","answer":"Event handling manages user actions."},
{"question":"What is form validation?","answer":"Validation checks input data."},
{"question":"What is accessibility?","answer":"Accessibility supports all users."},
{"question":"What is SEO?","answer":"SEO improves search ranking."},
{"question":"What is cross browser compatibility?","answer":"Works across browsers."},
{"question":"What is flexbox?","answer":"Flexbox layouts elements."},
{"question":"What is grid?","answer":"Grid creates layout system."},
{"question":"Explain lifecycle methods.","answer":"Lifecycle manages component stages."},
{"question":"What is npm?","answer":"npm manages packages."},
{"question":"What is webpack?","answer":"Webpack bundles files."},
{"question":"What is Babel?","answer":"Babel compiles JS."},
{"question":"What is TypeScript?","answer":"TypeScript adds types to JS."},
{"question":"What is performance optimization?","answer":"Improves speed and efficiency."},
{"question":"What is lazy loading?","answer":"Loads components on demand."},
{"question":"What is code splitting?","answer":"Splits code into chunks."},
{"question":"What is testing?","answer":"Testing verifies functionality."},
{"question":"What is Jest?","answer":"Jest testing framework."},
{"question":"What is version control?","answer":"Tracks code changes."},
{"question":"Explain project architecture.","answer":"Modular component based structure."},
{"question":"What is UI?","answer":"User interface design."},
{"question":"What is UX?","answer":"User experience design."},
{"question":"What is animation?","answer":"Adds motion to UI."},
{"question":"What is debugging?","answer":"Fixing code errors."},
{"question":"What is deployment?","answer":"Publishing app online."},
{"question":"What is hosting?","answer":"Server stores website."},
{"question":"What is CDN?","answer":"Content delivery network."},
{"question":"Explain your frontend project.","answer":"Frontend project built using React and API integration."},
{"question":"Why frontend important?","answer":"Frontend improves user interaction."}
],
"Backend Developer": [
{"question":"What is backend development?","answer":"Backend handles server and database logic."},
{"question":"What is Node.js?","answer":"Node.js runs JavaScript on server."},
{"question":"What is Express.js?","answer":"Express builds server APIs."},
{"question":"What is API?","answer":"API connects frontend and backend."},
{"question":"What is REST?","answer":"REST is architectural style for APIs."},
{"question":"What is CRUD?","answer":"Create Read Update Delete operations."},
{"question":"What is middleware?","answer":"Middleware processes requests."},
{"question":"What is JWT?","answer":"JWT handles authentication tokens."},
{"question":"What is authentication?","answer":"Authentication verifies identity."},
{"question":"What is authorization?","answer":"Authorization grants access."},
{"question":"What is MongoDB?","answer":"MongoDB is NoSQL database."},
{"question":"What is Mongoose?","answer":"Mongoose connects Node with MongoDB."},
{"question":"What is SQL?","answer":"SQL manages relational databases."},
{"question":"What is MySQL?","answer":"MySQL relational database."},
{"question":"What is PostgreSQL?","answer":"PostgreSQL advanced SQL database."},
{"question":"What is indexing?","answer":"Indexing improves query speed."},
{"question":"What is hashing?","answer":"Hashing secures passwords."},
{"question":"What is bcrypt?","answer":"bcrypt hashes passwords."},
{"question":"What is session?","answer":"Session stores user data."},
{"question":"What is cookies?","answer":"Cookies store small client data."},
{"question":"What is MVC?","answer":"Model View Controller architecture."},
{"question":"What is environment variable?","answer":"Stores config values securely."},
{"question":"What is CORS?","answer":"CORS controls cross origin requests."},
{"question":"What is rate limiting?","answer":"Limits API request frequency."},
{"question":"What is validation?","answer":"Validates input data."},
{"question":"What is error handling?","answer":"Manages application errors."},
{"question":"What is logging?","answer":"Tracks backend activity."},
{"question":"What is deployment?","answer":"Hosting backend on server."},
{"question":"What is cloud server?","answer":"Server hosted online."},
{"question":"What is Docker?","answer":"Containerizes backend app."},
{"question":"What is scalability?","answer":"Handles increasing load."},
{"question":"What is microservices?","answer":"Splits app into services."},
{"question":"What is monolith?","answer":"Single large application."},
{"question":"What is caching?","answer":"Stores data for fast access."},
{"question":"What is Redis?","answer":"Redis in memory database."},
{"question":"What is WebSocket?","answer":"Real time communication protocol."},
{"question":"What is GraphQL?","answer":"Flexible API query language."},
{"question":"What is ORM?","answer":"Object relational mapping tool."},
{"question":"What is Sequelize?","answer":"ORM for SQL in Node."},
{"question":"What is API testing?","answer":"Testing backend endpoints."},
{"question":"What is security?","answer":"Protecting backend data."},
{"question":"What is load balancing?","answer":"Distributes server traffic."},
{"question":"What is CI CD?","answer":"Automates deployment process."},
{"question":"What is version control?","answer":"Tracks code changes."},
{"question":"What is Git?","answer":"Version control system."},
{"question":"What is debugging?","answer":"Fixing server errors."},
{"question":"Explain backend architecture.","answer":"Layered architecture with API and database."},
{"question":"Explain your backend project.","answer":"Built REST API with authentication."},
{"question":"Why backend important?","answer":"Backend manages logic and data."},
{"question":"How to secure API?","answer":"Use authentication validation and encryption."}
],
"Cloud Engineer": [
{"question":"What is cloud computing?","answer":"Cloud delivers services over internet."},
{"question":"What is AWS?","answer":"Amazon cloud platform."},
{"question":"What is Azure?","answer":"Microsoft cloud platform."},
{"question":"What is GCP?","answer":"Google cloud platform."},
{"question":"What is EC2?","answer":"Virtual server in AWS."},
{"question":"What is S3?","answer":"Cloud storage service."},
{"question":"What is IAM?","answer":"Identity access management."},
{"question":"What is VPC?","answer":"Virtual private cloud."},
{"question":"What is load balancer?","answer":"Distributes cloud traffic."},
{"question":"What is auto scaling?","answer":"Adjusts resources automatically."},
{"question":"What is serverless?","answer":"Runs code without servers."},
{"question":"What is Lambda?","answer":"AWS serverless function."},
{"question":"What is cloud storage?","answer":"Stores data online."},
{"question":"What is CDN?","answer":"Content delivery network."},
{"question":"What is DNS?","answer":"Domain name system."},
{"question":"What is container?","answer":"Packages application dependencies."},
{"question":"What is Kubernetes?","answer":"Manages containers."},
{"question":"What is Docker?","answer":"Container platform."},
{"question":"What is Terraform?","answer":"Infrastructure as code tool."},
{"question":"What is monitoring?","answer":"Tracks cloud performance."},
{"question":"What is CloudWatch?","answer":"AWS monitoring service."},
{"question":"What is SLA?","answer":"Service level agreement."},
{"question":"What is availability zone?","answer":"Isolated cloud location."},
{"question":"What is region?","answer":"Geographical cloud area."},
{"question":"What is encryption?","answer":"Secures cloud data."},
{"question":"What is backup?","answer":"Data recovery method."},
{"question":"What is disaster recovery?","answer":"Restores cloud services."},
{"question":"What is cost optimization?","answer":"Reduces cloud expenses."},
{"question":"What is hybrid cloud?","answer":"Mix of cloud and local."},
{"question":"What is multi cloud?","answer":"Using multiple cloud providers."},
{"question":"What is private cloud?","answer":"Dedicated cloud environment."},
{"question":"What is public cloud?","answer":"Shared cloud services."},
{"question":"What is networking?","answer":"Cloud communication setup."},
{"question":"What is API gateway?","answer":"Manages API traffic."},
{"question":"What is DevOps?","answer":"Development and operations integration."},
{"question":"What is CI CD?","answer":"Automated deployment pipeline."},
{"question":"What is logging?","answer":"Tracks cloud events."},
{"question":"What is IAM role?","answer":"Grants service permissions."},
{"question":"What is object storage?","answer":"Stores data as objects."},
{"question":"What is block storage?","answer":"Stores data in blocks."},
{"question":"What is database service?","answer":"Managed cloud database."},
{"question":"What is RDS?","answer":"AWS relational database service."},
{"question":"What is scalability?","answer":"Handles traffic growth."},
{"question":"What is security group?","answer":"Firewall for cloud."},
{"question":"What is container registry?","answer":"Stores container images."},
{"question":"What is deployment?","answer":"Publishing cloud app."},
{"question":"Explain cloud architecture.","answer":"Scalable distributed infrastructure."},
{"question":"Explain your cloud project.","answer":"Deployed app on AWS."},
{"question":"Why cloud important?","answer":"Provides scalable infrastructure."},
{"question":"Future of cloud?","answer":"Growing demand worldwide."}
],
"AI Engineer": [
{"question":"What is Artificial Intelligence?","answer":"AI enables machines to mimic human intelligence."},
{"question":"What is Machine Learning?","answer":"ML allows systems to learn from data."},
{"question":"What is Deep Learning?","answer":"Deep learning uses neural networks."},
{"question":"What is supervised learning?","answer":"Learning with labeled data."},
{"question":"What is unsupervised learning?","answer":"Learning without labeled data."},
{"question":"What is reinforcement learning?","answer":"Learning using rewards and penalties."},
{"question":"What is neural network?","answer":"Model inspired by human brain."},
{"question":"What is overfitting?","answer":"Model performs well on training but poor on test."},
{"question":"What is underfitting?","answer":"Model fails to capture patterns."},
{"question":"What is dataset?","answer":"Collection of training data."},
{"question":"What is feature engineering?","answer":"Selecting important input variables."},
{"question":"What is model evaluation?","answer":"Measuring model performance."},
{"question":"What is accuracy?","answer":"Correct prediction percentage."},
{"question":"What is precision?","answer":"Correct positive predictions ratio."},
{"question":"What is recall?","answer":"Detected positive cases ratio."},
{"question":"What is F1 score?","answer":"Harmonic mean of precision and recall."},
{"question":"What is confusion matrix?","answer":"Table of prediction results."},
{"question":"What is regression?","answer":"Predicting continuous values."},
{"question":"What is classification?","answer":"Predicting categories."},
{"question":"What is clustering?","answer":"Grouping similar data."},
{"question":"What is NLP?","answer":"Natural language processing of text."},
{"question":"What is computer vision?","answer":"AI understanding images."},
{"question":"What is TensorFlow?","answer":"Google ML framework."},
{"question":"What is PyTorch?","answer":"Deep learning framework."},
{"question":"What is scikit-learn?","answer":"Python ML library."},
{"question":"What is training?","answer":"Teaching model using data."},
{"question":"What is testing?","answer":"Evaluating model performance."},
{"question":"What is validation?","answer":"Tuning model parameters."},
{"question":"What is bias?","answer":"Systematic prediction error."},
{"question":"What is variance?","answer":"Model sensitivity to data."},
{"question":"What is gradient descent?","answer":"Optimization algorithm."},
{"question":"What is loss function?","answer":"Measures prediction error."},
{"question":"What is activation function?","answer":"Adds non-linearity."},
{"question":"What is CNN?","answer":"Convolutional neural network."},
{"question":"What is RNN?","answer":"Recurrent neural network."},
{"question":"What is LSTM?","answer":"Long short term memory network."},
{"question":"What is transformer?","answer":"Attention based model."},
{"question":"What is Chatbot?","answer":"AI conversational system."},
{"question":"What is generative AI?","answer":"AI that creates content."},
{"question":"What is prompt engineering?","answer":"Designing input prompts for AI."},
{"question":"What is data preprocessing?","answer":"Cleaning and preparing data."},
{"question":"What is normalization?","answer":"Scaling data values."},
{"question":"What is cross validation?","answer":"Model performance testing technique."},
{"question":"What is hyperparameter tuning?","answer":"Optimizing model settings."},
{"question":"What is deployment?","answer":"Making model live."},
{"question":"Explain your AI project.","answer":"Built ML model and deployed API."},
{"question":"What is model drift?","answer":"Model performance degradation."},
{"question":"What is transfer learning?","answer":"Using pre-trained models."},
{"question":"Why AI important?","answer":"Automates intelligent tasks."},
{"question":"Future of AI?","answer":"Rapid growth across industries."}
],
"Mobile Developer": [
{"question":"What is mobile development?","answer":"Building applications for mobile devices."},
{"question":"What is Android?","answer":"Google mobile operating system."},
{"question":"What is iOS?","answer":"Apple mobile operating system."},
{"question":"What is Flutter?","answer":"Cross platform UI toolkit."},
{"question":"What is React Native?","answer":"JS framework for mobile apps."},
{"question":"What is Kotlin?","answer":"Android programming language."},
{"question":"What is Swift?","answer":"iOS programming language."},
{"question":"What is APK?","answer":"Android app package."},
{"question":"What is emulator?","answer":"Virtual device for testing."},
{"question":"What is SDK?","answer":"Software development kit."},
{"question":"What is UI?","answer":"User interface design."},
{"question":"What is responsive design?","answer":"Adapts to screen sizes."},
{"question":"What is API integration?","answer":"Connecting backend services."},
{"question":"What is Firebase?","answer":"Backend service platform."},
{"question":"What is push notification?","answer":"App message alert."},
{"question":"What is local storage?","answer":"Data stored on device."},
{"question":"What is SQLite?","answer":"Mobile database."},
{"question":"What is state management?","answer":"Handling app data flow."},
{"question":"What is lifecycle?","answer":"App activity stages."},
{"question":"What is debugging?","answer":"Fixing mobile errors."},
{"question":"What is testing?","answer":"Verifying app functionality."},
{"question":"What is deployment?","answer":"Publishing to app store."},
{"question":"What is Play Store?","answer":"Android app marketplace."},
{"question":"What is App Store?","answer":"iOS app marketplace."},
{"question":"What is hybrid app?","answer":"Cross platform app."},
{"question":"What is native app?","answer":"Platform specific app."},
{"question":"What is performance optimization?","answer":"Improving app speed."},
{"question":"What is memory management?","answer":"Managing device memory."},
{"question":"What is REST API?","answer":"Backend communication method."},
{"question":"What is version control?","answer":"Tracking code changes."},
{"question":"Explain your mobile project.","answer":"Built cross platform app with API."},
{"question":"What is animation?","answer":"UI motion effects."},
{"question":"What is navigation?","answer":"Moving between screens."},
{"question":"What is permission handling?","answer":"Managing device access."},
{"question":"What is security?","answer":"Protecting app data."},
{"question":"What is CI CD?","answer":"Automated build deployment."},
{"question":"What is crash reporting?","answer":"Tracking app failures."},
{"question":"What is cloud messaging?","answer":"Sending remote notifications."},
{"question":"What is UI testing?","answer":"Testing user interface."},
{"question":"Why mobile development important?","answer":"Mobile apps dominate usage."},
{"question":"Future of mobile apps?","answer":"Growing rapidly worldwide."}
],
"Software Tester": [
{"question":"What is software testing?","answer":"Testing verifies software quality."},
{"question":"What is manual testing?","answer":"Testing without automation tools."},
{"question":"What is automation testing?","answer":"Testing using scripts and tools."},
{"question":"What is unit testing?","answer":"Testing individual components."},
{"question":"What is integration testing?","answer":"Testing combined modules."},
{"question":"What is system testing?","answer":"Testing complete application."},
{"question":"What is regression testing?","answer":"Testing after changes."},
{"question":"What is smoke testing?","answer":"Basic functionality testing."},
{"question":"What is sanity testing?","answer":"Quick verification testing."},
{"question":"What is black box testing?","answer":"Testing without code knowledge."},
{"question":"What is white box testing?","answer":"Testing with code knowledge."},
{"question":"What is test case?","answer":"Documented testing scenario."},
{"question":"What is test plan?","answer":"Testing strategy document."},
{"question":"What is bug?","answer":"Software defect."},
{"question":"What is defect life cycle?","answer":"Stages of bug handling."},
{"question":"What is Selenium?","answer":"Automation testing tool."},
{"question":"What is JUnit?","answer":"Java testing framework."},
{"question":"What is API testing?","answer":"Testing backend APIs."},
{"question":"What is performance testing?","answer":"Testing speed and stability."},
{"question":"What is load testing?","answer":"Testing under heavy traffic."},
{"question":"What is stress testing?","answer":"Testing beyond limits."},
{"question":"What is usability testing?","answer":"Testing user experience."},
{"question":"What is security testing?","answer":"Testing vulnerabilities."},
{"question":"What is test automation framework?","answer":"Structure for automation scripts."},
{"question":"What is CI CD in testing?","answer":"Automated testing pipeline."},
{"question":"What is test scenario?","answer":"High level testing idea."},
{"question":"What is test script?","answer":"Automation code script."},
{"question":"What is alpha testing?","answer":"Internal user testing."},
{"question":"What is beta testing?","answer":"External user testing."},
{"question":"What is exploratory testing?","answer":"Adhoc testing approach."},
{"question":"What is boundary testing?","answer":"Testing edge values."},
{"question":"What is equivalence partitioning?","answer":"Dividing input into classes."},
{"question":"What is test coverage?","answer":"Amount of code tested."},
{"question":"What is defect severity?","answer":"Impact of bug."},
{"question":"What is defect priority?","answer":"Urgency to fix bug."},
{"question":"What is Agile testing?","answer":"Testing in agile process."},
{"question":"What is SDLC?","answer":"Software development life cycle."},
{"question":"What is STLC?","answer":"Software testing life cycle."},
{"question":"What is bug report?","answer":"Documented defect details."},
{"question":"What is test environment?","answer":"Setup for testing."},
{"question":"What is version control?","answer":"Tracking code changes."},
{"question":"Explain your testing project.","answer":"Tested application manually and automated."},
{"question":"What is mobile testing?","answer":"Testing mobile apps."},
{"question":"What is database testing?","answer":"Testing database functionality."},
{"question":"What is UI testing?","answer":"Testing user interface."},
{"question":"What is API validation?","answer":"Verifying API responses."},
{"question":"What is risk analysis?","answer":"Identifying testing risks."},
{"question":"What is defect tracking tool?","answer":"Tool to track bugs."},
{"question":"Why testing important?","answer":"Ensures software quality."},
{"question":"Future of testing?","answer":"Automation and AI driven testing."}
],
"Blockchain Developer": [
{"question":"What is blockchain?","answer":"Distributed digital ledger."},
{"question":"What is cryptocurrency?","answer":"Digital currency on blockchain."},
{"question":"What is Bitcoin?","answer":"First cryptocurrency."},
{"question":"What is Ethereum?","answer":"Smart contract blockchain."},
{"question":"What is smart contract?","answer":"Self executing digital contract."},
{"question":"What is decentralization?","answer":"No central authority."},
{"question":"What is mining?","answer":"Validating blockchain transactions."},
{"question":"What is hash?","answer":"Cryptographic fixed output."},
{"question":"What is consensus?","answer":"Agreement mechanism in network."},
{"question":"What is proof of work?","answer":"Mining based consensus."},
{"question":"What is proof of stake?","answer":"Stake based consensus."},
{"question":"What is wallet?","answer":"Stores crypto keys."},
{"question":"What is private key?","answer":"Secret access key."},
{"question":"What is public key?","answer":"Public address key."},
{"question":"What is gas fee?","answer":"Transaction fee in Ethereum."},
{"question":"What is Solidity?","answer":"Smart contract language."},
{"question":"What is NFT?","answer":"Non fungible token."},
{"question":"What is DeFi?","answer":"Decentralized finance."},
{"question":"What is DAO?","answer":"Decentralized autonomous organization."},
{"question":"What is tokenization?","answer":"Converting assets into tokens."},
{"question":"What is dApp?","answer":"Decentralized application."},
{"question":"What is ledger?","answer":"Transaction record book."},
{"question":"What is block?","answer":"Group of transactions."},
{"question":"What is node?","answer":"Network participant."},
{"question":"What is chain?","answer":"Linked blocks."},
{"question":"What is double spending?","answer":"Spending crypto twice."},
{"question":"What is blockchain security?","answer":"Cryptographic data protection."},
{"question":"What is web3?","answer":"Decentralized web."},
{"question":"Explain your blockchain project.","answer":"Built smart contract and deployed."},
{"question":"Future of blockchain?","answer":"Growing decentralized systems."}
],
"Game Developer": [
{"question":"What is game development?","answer":"Creating interactive digital games."},
{"question":"What is Unity?","answer":"Popular cross platform game engine."},
{"question":"What is Unreal Engine?","answer":"Advanced 3D game engine."},
{"question":"What is game loop?","answer":"Continuous update render cycle."},
{"question":"What is FPS?","answer":"Frames rendered per second."},
{"question":"What is sprite?","answer":"2D image object in game."},
{"question":"What is collider?","answer":"Detects object collision."},
{"question":"What is rigidbody?","answer":"Adds physics properties."},
{"question":"What is physics engine?","answer":"Simulates real world physics."},
{"question":"What is animation?","answer":"Movement of characters."},
{"question":"What is rendering?","answer":"Drawing graphics on screen."},
{"question":"What is shader?","answer":"Program controlling graphics rendering."},
{"question":"What is texture?","answer":"Surface image applied to model."},
{"question":"What is AI in games?","answer":"Logic for NPC behavior."},
{"question":"What is pathfinding?","answer":"Finding shortest route in game."},
{"question":"What is multiplayer?","answer":"Multiple players playing together."},
{"question":"What is networking in games?","answer":"Connecting players online."},
{"question":"What is latency?","answer":"Delay in game response."},
{"question":"What is hitbox?","answer":"Collision detection area."},
{"question":"What is game physics?","answer":"Simulated gravity and motion."},
{"question":"What is particle system?","answer":"Visual effects like fire."},
{"question":"What is level design?","answer":"Designing game stages."},
{"question":"What is asset?","answer":"Game resource file."},
{"question":"What is scripting?","answer":"Writing game logic code."},
{"question":"What is C# in Unity?","answer":"Primary scripting language."},
{"question":"What is blueprint in Unreal?","answer":"Visual scripting system."},
{"question":"What is optimization?","answer":"Improving performance."},
{"question":"What is debugging?","answer":"Fixing game errors."},
{"question":"What is game engine?","answer":"Software framework for games."},
{"question":"What is VR?","answer":"Virtual reality gaming."},
{"question":"What is AR?","answer":"Augmented reality gaming."},
{"question":"What is cross platform game?","answer":"Runs on multiple devices."},
{"question":"What is 2D game?","answer":"Two dimensional gameplay."},
{"question":"What is 3D game?","answer":"Three dimensional gameplay."},
{"question":"What is UI in games?","answer":"User interface elements."},
{"question":"What is sound design?","answer":"Audio creation for games."},
{"question":"What is monetization?","answer":"Game revenue strategy."},
{"question":"What is in-app purchase?","answer":"Buying items inside game."},
{"question":"What is game testing?","answer":"Testing gameplay quality."},
{"question":"What is beta testing?","answer":"User testing phase."},
{"question":"What is version control?","answer":"Tracking code changes."},
{"question":"What is Git?","answer":"Version control tool."},
{"question":"What is repository?","answer":"Code storage location."},
{"question":"What is deployment?","answer":"Publishing game."},
{"question":"What is Play Store?","answer":"Android game marketplace."},
{"question":"What is Steam?","answer":"PC game distribution platform."},
{"question":"What is storyline?","answer":"Game narrative structure."},
{"question":"Explain your game project.","answer":"Developed interactive playable game."},
{"question":"Challenges in game dev?","answer":"Optimization and performance issues."},
{"question":"Future of gaming?","answer":"AR VR and cloud gaming growth."}
],
"UI UX Designer": [
{"question":"What is UI?","answer":"User interface design."},
{"question":"What is UX?","answer":"User experience design."},
{"question":"Difference between UI and UX?","answer":"UI is look UX is feel."},
{"question":"What is wireframe?","answer":"Basic layout blueprint."},
{"question":"What is prototype?","answer":"Interactive mock design."},
{"question":"What is Figma?","answer":"UI design tool."},
{"question":"What is Adobe XD?","answer":"Design prototyping tool."},
{"question":"What is user research?","answer":"Studying user needs."},
{"question":"What is persona?","answer":"Fictional user profile."},
{"question":"What is usability?","answer":"Ease of using product."},
{"question":"What is accessibility?","answer":"Design for all users."},
{"question":"What is typography?","answer":"Font styling design."},
{"question":"What is color theory?","answer":"Color design principles."},
{"question":"What is responsive design?","answer":"Adapts to devices."},
{"question":"What is grid system?","answer":"Layout alignment structure."},
{"question":"What is visual hierarchy?","answer":"Importance order in design."},
{"question":"What is interaction design?","answer":"User interaction planning."},
{"question":"What is microinteraction?","answer":"Small UI animations."},
{"question":"What is design thinking?","answer":"Problem solving approach."},
{"question":"What is A/B testing?","answer":"Comparing design versions."},
{"question":"What is heuristic evaluation?","answer":"Usability inspection method."},
{"question":"What is user flow?","answer":"User navigation path."},
{"question":"What is sitemap?","answer":"Website structure map."},
{"question":"What is low fidelity design?","answer":"Basic rough design."},
{"question":"What is high fidelity design?","answer":"Detailed final design."},
{"question":"What is mockup?","answer":"Visual design preview."},
{"question":"What is dashboard design?","answer":"Data visualization interface."},
{"question":"What is mobile first design?","answer":"Designing for mobile first."},
{"question":"What is consistency?","answer":"Uniform design elements."},
{"question":"What is contrast?","answer":"Difference in design elements."},
{"question":"What is whitespace?","answer":"Empty design space."},
{"question":"What is branding?","answer":"Visual identity creation."},
{"question":"What is design system?","answer":"Reusable design components."},
{"question":"What is iconography?","answer":"Icon design usage."},
{"question":"What is prototyping tool?","answer":"Tool for interactive preview."},
{"question":"What is user journey?","answer":"Complete user experience path."},
{"question":"What is empathy mapping?","answer":"Understanding user emotions."},
{"question":"What is usability testing?","answer":"Testing design with users."},
{"question":"What is feedback loop?","answer":"Collecting user feedback."},
{"question":"What is UI kit?","answer":"Prebuilt design elements."},
{"question":"What is dark mode design?","answer":"Dark theme interface."},
{"question":"What is minimalism?","answer":"Simple clean design style."},
{"question":"What is CTA?","answer":"Call to action button."},
{"question":"What is onboarding design?","answer":"First time user guidance."},
{"question":"What is portfolio?","answer":"Showcase of design work."},
{"question":"Explain your design project.","answer":"Designed responsive user friendly interface."},
{"question":"Why UX important?","answer":"Improves user satisfaction."},
{"question":"Future of UI UX?","answer":"AI driven personalization."},
{"question":"Tools you use?","answer":"Figma Adobe XD."},
{"question":"How handle feedback?","answer":"Iterate design improvements."}
],
"Full Stack Developer": [
{"question":"What is full stack development?","answer":"Frontend and backend development combined."},
{"question":"What is frontend?","answer":"Client side user interface."},
{"question":"What is backend?","answer":"Server side logic and database."},
{"question":"What is MERN stack?","answer":"MongoDB Express React Node."},
{"question":"What is MEAN stack?","answer":"MongoDB Express Angular Node."},
{"question":"What is REST API?","answer":"Standard backend communication interface."},
{"question":"What is CRUD?","answer":"Create Read Update Delete operations."},
{"question":"What is authentication?","answer":"Verifying user identity."},
{"question":"What is authorization?","answer":"Granting user permissions."},
{"question":"What is JWT?","answer":"Token based authentication system."},
{"question":"What is session?","answer":"Server stored user state."},
{"question":"What is cookies?","answer":"Client side small data storage."},
{"question":"What is MongoDB?","answer":"NoSQL document database."},
{"question":"What is MySQL?","answer":"Relational SQL database."},
{"question":"What is API integration?","answer":"Connecting frontend with backend."},
{"question":"What is middleware?","answer":"Request processing function."},
{"question":"What is MVC?","answer":"Model View Controller architecture."},
{"question":"What is deployment?","answer":"Publishing application online."},
{"question":"What is hosting?","answer":"Server providing app access."},
{"question":"What is Git?","answer":"Version control system."},
{"question":"What is GitHub?","answer":"Online Git repository platform."},
{"question":"What is environment variable?","answer":"Secure configuration variable."},
{"question":"What is CORS?","answer":"Cross origin resource sharing policy."},
{"question":"What is validation?","answer":"Checking input data correctness."},
{"question":"What is error handling?","answer":"Managing runtime errors."},
{"question":"What is responsive design?","answer":"Adapting UI to devices."},
{"question":"What is state management?","answer":"Handling application data flow."},
{"question":"What is Redux?","answer":"Global state management library."},
{"question":"What is Express.js?","answer":"Backend framework for Node."},
{"question":"What is Node.js?","answer":"JavaScript runtime environment."},
{"question":"What is React?","answer":"Frontend UI library."},
{"question":"What is database indexing?","answer":"Improving query performance."},
{"question":"What is hashing?","answer":"Securing passwords."},
{"question":"What is bcrypt?","answer":"Password hashing library."},
{"question":"What is API testing?","answer":"Testing backend endpoints."},
{"question":"What is scalability?","answer":"Handling growing users."},
{"question":"What is caching?","answer":"Storing data for faster access."},
{"question":"What is Redis?","answer":"In memory caching database."},
{"question":"What is WebSocket?","answer":"Real time communication protocol."},
{"question":"What is CI CD?","answer":"Automated build and deployment."},
{"question":"What is Docker?","answer":"Application containerization tool."},
{"question":"What is cloud hosting?","answer":"Deploying app on cloud."},
{"question":"What is performance optimization?","answer":"Improving speed and efficiency."},
{"question":"What is testing?","answer":"Verifying application quality."},
{"question":"What is Agile?","answer":"Iterative development methodology."},
{"question":"What is SDLC?","answer":"Software development life cycle."},
{"question":"Explain your full stack project.","answer":"Built complete web app with frontend backend database."},
{"question":"Challenges faced?","answer":"Authentication and deployment issues."},
{"question":"Why full stack role?","answer":"Ability to handle complete system."},
{"question":"Future of full stack?","answer":"High demand across industries."}
],
"Database Administrator": [
{"question":"Who is a DBA?","answer":"Person managing databases."},
{"question":"What is database?","answer":"Organized data storage system."},
{"question":"What is SQL?","answer":"Structured query language."},
{"question":"What is normalization?","answer":"Reducing data redundancy."},
{"question":"What is denormalization?","answer":"Adding redundancy for performance."},
{"question":"What is primary key?","answer":"Unique identifier column."},
{"question":"What is foreign key?","answer":"Reference to primary key."},
{"question":"What is indexing?","answer":"Improving query speed."},
{"question":"What is backup?","answer":"Copy of database data."},
{"question":"What is restore?","answer":"Recovering database from backup."},
{"question":"What is transaction?","answer":"Single database operation unit."},
{"question":"What is ACID?","answer":"Database reliability properties."},
{"question":"What is isolation level?","answer":"Transaction visibility control."},
{"question":"What is deadlock?","answer":"Two transactions blocking each other."},
{"question":"What is stored procedure?","answer":"Precompiled SQL code."},
{"question":"What is trigger?","answer":"Automatic database action."},
{"question":"What is view?","answer":"Virtual table."},
{"question":"What is schema?","answer":"Database structure definition."},
{"question":"What is replication?","answer":"Copying data to another server."},
{"question":"What is sharding?","answer":"Splitting database horizontally."},
{"question":"What is partitioning?","answer":"Dividing table data."},
{"question":"What is data migration?","answer":"Moving data between systems."},
{"question":"What is performance tuning?","answer":"Optimizing database speed."},
{"question":"What is query optimization?","answer":"Improving SQL performance."},
{"question":"What is indexing types?","answer":"Clustered and non clustered."},
{"question":"What is NoSQL?","answer":"Non relational database."},
{"question":"What is MongoDB?","answer":"Document based NoSQL database."},
{"question":"What is MySQL?","answer":"Relational database system."},
{"question":"What is PostgreSQL?","answer":"Advanced relational database."},
{"question":"What is data integrity?","answer":"Accuracy and consistency of data."},
{"question":"What is constraint?","answer":"Rule applied on column."},
{"question":"What is unique constraint?","answer":"Prevents duplicate values."},
{"question":"What is not null?","answer":"Disallows null values."},
{"question":"What is default constraint?","answer":"Default column value."},
{"question":"What is join?","answer":"Combining tables data."},
{"question":"Types of joins?","answer":"Inner left right full join."},
{"question":"What is subquery?","answer":"Query inside another query."},
{"question":"What is aggregate function?","answer":"SUM COUNT AVG etc."},
{"question":"What is data warehouse?","answer":"Centralized data storage."},
{"question":"What is ETL?","answer":"Extract transform load process."},
{"question":"What is indexing advantage?","answer":"Faster data retrieval."},
{"question":"What is log file?","answer":"Database transaction record."},
{"question":"What is database security?","answer":"Protecting database access."},
{"question":"What is user role?","answer":"Permission management."},
{"question":"What is monitoring?","answer":"Tracking database health."},
{"question":"What is high availability?","answer":"Minimizing downtime."},
{"question":"Explain your database project.","answer":"Designed optimized relational database."},
{"question":"Challenges in DBA?","answer":"Performance and backup management."},
{"question":"Why DBA important?","answer":"Ensures reliable data management."},
{"question":"Future of databases?","answer":"Cloud and distributed databases."}
],
}